#:schema node_modules/wrangler/config-schema.json
name = "weather-along-route"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[assets]
directory = "./public"

[[routes]]
pattern = "weatheralongroute.mapki.com"
custom_domain = true
